
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fernando Alberto
 */
public class Menu_Admin extends javax.swing.JFrame {

    DefaultTableModel modeloTabla_Clientes = new DefaultTableModel();
    DefaultTableModel modeloTabla_Distribuidores = new DefaultTableModel();
    DefaultTableModel modeloTabla_Reportes = new DefaultTableModel();
    
    public Menu_Admin() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        Principal.LeerTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jpanel_Clientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        jpanel_Distribuidores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDistribuidor = new javax.swing.JTable();
        jpanel_Reportes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtReportes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane3.setBackground(new java.awt.Color(102, 0, 0));
        jTabbedPane3.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setAlignmentX(1.0F);
        jTabbedPane3.setAlignmentY(1.0F);
        jTabbedPane3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jtClientes.setBorder(new javax.swing.border.MatteBorder(null));
        jtClientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtClientes.setEnabled(false);
        jtClientes.setFocusable(false);
        jtClientes.setIntercellSpacing(new java.awt.Dimension(3, 4));
        jtClientes.setRowHeight(25);
        jtClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtClientes);

        javax.swing.GroupLayout jpanel_ClientesLayout = new javax.swing.GroupLayout(jpanel_Clientes);
        jpanel_Clientes.setLayout(jpanel_ClientesLayout);
        jpanel_ClientesLayout.setHorizontalGroup(
            jpanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        jpanel_ClientesLayout.setVerticalGroup(
            jpanel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Clientes", jpanel_Clientes);

        jtDistribuidor.setBorder(new javax.swing.border.MatteBorder(null));
        jtDistribuidor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtDistribuidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtDistribuidor.setEnabled(false);
        jtDistribuidor.setFocusable(false);
        jtDistribuidor.setIntercellSpacing(new java.awt.Dimension(3, 4));
        jtDistribuidor.setRowHeight(25);
        jtDistribuidor.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtDistribuidor);

        javax.swing.GroupLayout jpanel_DistribuidoresLayout = new javax.swing.GroupLayout(jpanel_Distribuidores);
        jpanel_Distribuidores.setLayout(jpanel_DistribuidoresLayout);
        jpanel_DistribuidoresLayout.setHorizontalGroup(
            jpanel_DistribuidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        jpanel_DistribuidoresLayout.setVerticalGroup(
            jpanel_DistribuidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Distribuidores", jpanel_Distribuidores);

        jtReportes.setBorder(new javax.swing.border.MatteBorder(null));
        jtReportes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtReportes.setEnabled(false);
        jtReportes.setFocusable(false);
        jtReportes.setRowHeight(25);
        jtReportes.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtReportes);

        javax.swing.GroupLayout jpanel_ReportesLayout = new javax.swing.GroupLayout(jpanel_Reportes);
        jpanel_Reportes.setLayout(jpanel_ReportesLayout);
        jpanel_ReportesLayout.setHorizontalGroup(
            jpanel_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        jpanel_ReportesLayout.setVerticalGroup(
            jpanel_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Reportes", jpanel_Reportes);

        jMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(153, 153, 153)));
        jMenu1.setText("Agregar");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem1.setText("Agregar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem2.setText("Agregar Distribuidor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(153, 153, 153)));
        jMenu3.setText("Gestionamiento");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem8.setText("Editar Ciente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem6.setText("Eliminar Cliente");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem9.setText("Editar Distribuidor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem7.setText("Eliminar Distribuidor");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Realizar");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem3.setText("Realizar Venta");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem4.setText("Realizar Abono");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenuItem5.setText("Consulta");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            Principal.LeerTodo();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu_Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Rellenar Tabla Clientes
        Object[] obj_Clientes= new Object[8];
        obj_Clientes[0]= "ID";
        obj_Clientes[1]= "Nombre";
        obj_Clientes[2]= "Telefono";
        obj_Clientes[3]= "Correo";
        obj_Clientes[4]= "Fecha de Nacimiento";
        obj_Clientes[5]= "Ciudad";
        obj_Clientes[6]= "Estatus";
        obj_Clientes[7]= "Sexo";
        
        modeloTabla_Clientes = new DefaultTableModel(obj_Clientes, Principal.ArrayClientes.size());
        jtClientes.setModel(modeloTabla_Clientes);
        try{
        for(int x=0; x<Principal.ArrayClientes.size(); x++)
        {
            jtClientes.setValueAt(Principal.ArrayClientes.get(x).getID(), x, 0);
            jtClientes.setValueAt(Principal.ArrayClientes.get(x).getNombre() + " " + Principal.ArrayClientes.get(x).getApellido_Paterno()+ " " + Principal.ArrayClientes.get(x).getApellido_Materno(), x, 1);
            jtClientes.setValueAt(Principal.ArrayClientes.get(x).getTelefono(), x, 2);
            jtClientes.setValueAt(Principal.ArrayClientes.get(x).getCorreo(), x, 3);
            jtClientes.setValueAt(Principal.ArrayClientes.get(x).getFecha_Nacimiento(), x, 4);
            jtClientes.setValueAt(Principal.ArrayClientes.get(x).getCiudad(), x, 5);
            jtClientes.setValueAt(Principal.ArrayClientes.get(x).getEstatus(), x, 6);
            jtClientes.setValueAt(Principal.ArrayClientes.get(x).getSexo(), x, 7);
        }
        }catch(Exception e){}
        
        //Rellenar Tabla Distribuidores
        Object[] obj_Distribuidores= new Object[8];
        obj_Distribuidores[0]= "ID";
        obj_Distribuidores[1]= "Nombre";
        obj_Distribuidores[2]= "Telefono";
        obj_Distribuidores[3]= "Dirección";
        obj_Distribuidores[4]= "Correo";
        obj_Distribuidores[5]= "Ciudad";
        obj_Distribuidores[6]= "Estado";
        obj_Distribuidores[7]= "Sexo";
        
        modeloTabla_Distribuidores = new DefaultTableModel(obj_Distribuidores, Principal.ArrayDistribuidores.size());
        jtDistribuidor.setModel(modeloTabla_Distribuidores);
        try{
        for(int x=0; x<Principal.ArrayDistribuidores.size(); x++)
        {
            jtDistribuidor.setValueAt(Principal.ArrayDistribuidores.get(x).getID(), x, 0);
            jtDistribuidor.setValueAt(Principal.ArrayDistribuidores.get(x).getNombres() + " " + Principal.ArrayDistribuidores.get(x).getApellido_Paterno()+ " " + Principal.ArrayDistribuidores.get(x).getApellido_Materno(), x, 1);
            jtDistribuidor.setValueAt(Principal.ArrayDistribuidores.get(x).getTelefono(), x, 2);
            jtDistribuidor.setValueAt(Principal.ArrayDistribuidores.get(x).getDireccion(), x, 3);
            jtDistribuidor.setValueAt(Principal.ArrayDistribuidores.get(x).getCorreo(), x, 4);
            jtDistribuidor.setValueAt(Principal.ArrayDistribuidores.get(x).getCiudad(), x, 5);
            jtDistribuidor.setValueAt(Principal.ArrayDistribuidores.get(x).getEstado(), x, 6);
            jtDistribuidor.setValueAt(Principal.ArrayDistribuidores.get(x).getSexo(), x, 7);
        }
        }catch(Exception e){}
        
        //Rellenar Tabla Distribuidores
        Object[] obj_Reportes= new Object[5];
        obj_Reportes[0]= "ID";
        obj_Reportes[1]= "Acción";
        obj_Reportes[2]= "Fecha";
        obj_Reportes[3]= "ID De Cliente";
        obj_Reportes[4]= "ID de Distribuidor";
        
        modeloTabla_Reportes = new DefaultTableModel(obj_Reportes, Principal.ArrayAbono.size() + Principal.ArrayVentas.size());
        jtReportes.setModel(modeloTabla_Reportes);
        try{
        for(int x=0; x<Principal.ArrayAbono.size(); x++){
            jtDistribuidor.setValueAt(Principal.ArrayAbono.get(x).getID_Pago(), x, 0);
            jtDistribuidor.setValueAt("Abono", x, 1);
            jtDistribuidor.setValueAt(Principal.ArrayAbono.get(x).getFecha(), x, 2);
            jtDistribuidor.setValueAt(Principal.ArrayAbono.get(x).getID_Cliente(), x, 3);
            jtDistribuidor.setValueAt(Principal.ArrayAbono.get(x).getID_Distribuidor(), x, 4);
        }
        }catch(Exception e){}
        try{
        for(int x=0; x<Principal.ArrayVentas.size(); x++){
            jtDistribuidor.setValueAt(Principal.ArrayVentas.get(x).getIDVenta(), x + Principal.ArrayAbono.size(), 0);
            jtDistribuidor.setValueAt("Venta", x, 1);
            jtDistribuidor.setValueAt(Principal.ArrayVentas.get(x).getFecha(), x + Principal.ArrayAbono.size(), 2);
            jtDistribuidor.setValueAt(Principal.ArrayVentas.get(x).getIDCliente(), x + Principal.ArrayAbono.size(), 3);
            jtDistribuidor.setValueAt(Principal.ArrayVentas.get(x).getIDDistribuidor(), x + Principal.ArrayAbono.size(), 4);
        }
        }catch(Exception e){}
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        IniciarSesion conector= new IniciarSesion();
        conector.setVisible(true);
        conector.setTitle("Iniciar Sesión");
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Añadir_Cliente conector= new Añadir_Cliente();
        conector.setVisible(true);
        conector.setTitle("Añadir Cliente");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Eliminar_Cliente conector= new Eliminar_Cliente();
        conector.setVisible(true);
        conector.setTitle("Eliminar Cliente");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Añadir_Distribuidor conector= new Añadir_Distribuidor();
        conector.setVisible(true);
        conector.setTitle("Añadir Distribuidor");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Eliminar_Distribuidor conector= new Eliminar_Distribuidor();
        conector.setVisible(true);
        conector.setTitle("Eliminar Distribuidor");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Editar_Cliente conector= new Editar_Cliente();
        conector.setVisible(true);
        conector.setTitle("Editar Cliente");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Editar_Distribuidor conector= new Editar_Distribuidor();
        conector.setVisible(true);
        conector.setTitle("Editar Distribuidores");
    }//GEN-LAST:event_jMenuItem9ActionPerformed
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu_Admin().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Menu_Admin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu_Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JPanel jpanel_Clientes;
    private javax.swing.JPanel jpanel_Distribuidores;
    private javax.swing.JPanel jpanel_Reportes;
    private javax.swing.JTable jtClientes;
    private javax.swing.JTable jtDistribuidor;
    private javax.swing.JTable jtReportes;
    // End of variables declaration//GEN-END:variables
}
